name: geok
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip: 
    - -r requirements.txt
  - bayesian-optimization
  - boto3
  - dvc
  - dython
  - ipykernel
  - python-confluent-kafka
  - make
  - minikube
  - pycaret
  - pyspark
  - scikit-optimize
  - seaborn
  - sklearn-genetic-opt
